=== practical-works/xml/_intro/type.dtd
<!DOCTYPE 
	Vente 
	[
		<!ELEMENT Vente (Produits)>
		<!ELEMENT Produits ( Produit+)>
		<!ELEMENT Produit (Produit_ID,Produit_Label)>
		<!ELEMENT Produit_ID (#PCDATA)>
		<!ELEMENT Produit_Label (#PCDATA)>
	]
>

=== practical-works/xml/_intro/Vente.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="style.css" type="text/css"?>
<!DOCTYPE Vente SYSTEM "type.dtd">
<Vente>
	<Produits>

		<Produit Produit_ID="1">
			<Produit_Label>clavier</Produit_Label>
		</Produit>

		<Produit Produit_ID="2">
			<Produit_Label>Souris</Produit_Label>
		</Produit>

		<Produit Produit_ID="3">
			<Produit_Label>Moniteur</Produit_Label>
		</Produit>

	</Produits>
</Vente>
